FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y vim && rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt

COPY server/ server/
COPY proto/ proto/

RUN python -m grpc_tools.protoc -I./proto --python_out=./server --grpc_python_out=./server ./proto/lms.proto

CMD ["python", "server/server.py"]
