FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y vim && rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt

COPY client/ client/
COPY proto/ proto/
COPY client/templates/ client/templates/
COPY client/static/ client/static/

RUN python -m grpc_tools.protoc -I./proto --python_out=./client --grpc_python_out=./client ./proto/lms.proto

CMD ["python", "client/app.py"]
